-- Free Plug — polish FreeForStudents deal listings already in DB
-- Generated by scripts/generate-freeforstudents-sql.mjs
-- Updates descriptions, tags (Deals + Online), and fixes a few source URLs

begin;

update listings set
  description = 'Prime Student includes 6 months of Amazon Prime free, then 50% off. Get fast shipping, Prime Video, exclusive deals, and 5% back on select purchases with an eligible Prime Visa card.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://www.amazon.com/amazonprime?primeCampaignId=studentWlpPrimeRedir&linkCode=sl2&tag=freeforstud0f-20&linkId=e241e0f9f7461c9a8622d5f73295ef98&language=en_US&ref_=as_li_ss_tl',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'prime-student-us';

update listings set
  description = 'Students save 70% on Proton VPN, a Swiss-based service with a strict no-logs policy. Connect through 140+ countries, access blocked content, and stay private on campus Wi‑Fi or abroad.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://freeforstudents.org/row#pricing',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'proton-vpn-70pc';

update listings set
  description = 'Prime Student members can stream Prime Video free for 6 months. Watch movies, series, and Amazon Originals on your laptop, phone, or TV.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://www.amazon.com/amazonprime?primeCampaignId=studentWlpPrimeRedir&linkCode=sl2&tag=freeforstud0f-20&linkId=e241e0f9f7461c9a8622d5f73295ef98&language=en_US&ref_=as_li_ss_tl',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'prime-video-us';

update listings set
  description = 'Prime members get Grubhub+ free for 6 months with $0 delivery on eligible orders from thousands of restaurants. A solid perk for late-night study sessions.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://www.amazon.com/amazonprime?primeCampaignId=studentWlpPrimeRedir&linkCode=ll2&tag=freeforstud0f-20&linkId=b1e3434607ef0d18acb94706a9887046&language=en_US&ref_=as_li_ss_tl#plp-slot-2',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'grubhub-prime';

update listings set
  description = 'Students get Apple Music for half price and Apple TV+ included free. Verify enrollment to unlock the discounted rate for up to 48 months.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://music.apple.com/us/student?itsct=kbj_stu&itscg=10000',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'apple-music-student';

update listings set
  description = 'Save 69% on NordVPN plus get 3 extra months free. Secure your connection on campus Wi‑Fi, dorm networks, and public hotspots.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://nordforme.org/offer/?utm_medium=affiliate&utm_term=&utm_content=2032346&utm_source=aff8110&utm_campaign=off226',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'nordvpn-69pc';

update listings set
  description = 'Mine helps students build credit and manage everyday spending without hidden fees. Built for college students who want to establish credit responsibly.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://usemine.com/lp/comparisonchart-2?irclickid=0QSSk5y8DxyZUqLxnr1IDVlsUkuVqu12cxbxSU0&impact_sharedid=&utm_source=impact&utm_medium=affiliate&utm_campaign=2032346&c_nm=FreeForStudents&utm_term=2364706&a_nm=Online%20Tracking%20Link&irgwc=1&afsrc=1',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'fizz-app';

update listings set
  description = 'Try Calm free for 30 days, then continue for $3.50/month as a student. Access guided meditations, sleep stories, and stress-relief tools between classes.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://www.calm.com/students',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'calm-prime-student';

update listings set
  description = 'AWS Educate offers free, self-paced cloud training and hands-on labs. Learn in-demand skills in cloud computing and AI with practice using services like S3 and EC2.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://freeforstudents.org/row/getting-started?nc1=f_cc',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'aws-educate';

update listings set
  description = 'College students get one free year of YNAB (You Need A Budget). Track spending, plan ahead, and build better money habits—verify with a student ID, transcript, or tuition statement.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://freeforstudents.org/row/guide/the-ultimate-get-started-guide',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'ynab-college';

update listings set
  description = 'Students save 50% on DataCamp. Access interactive courses in data science, Python, R, SQL, and AI to build job-ready skills at your own pace.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://www.datacamp.com/pricing/student?irclickid=xzQQbfy8DxyZUqLxnr1IDVlsUkuVqu3GcxbxSU0&irgwc=1&afsrc=1&utm_medium=affiliate&utm_source=impact&utm_campaign=000000_1-2032346_2-mix_3-all_4-na_5-na_6-na_7-mp_8-affl-ip_9-na_10-bau_11-FreeForStudents&utm_content=ONLINE_TRACKING_LINK&utm_term=',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'datacamp-student-50pc';

update listings set
  description = 'Students can claim a free .me domain and discounts on other domains through Namecheap''s education hub. Great for portfolios, side projects, and personal sites.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://www.namecheap.com/build-and-grow-hub/',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'namecheap';

update listings set
  description = 'Get 30% off an annual Skillshare membership. Explore thousands of classes in design, video, marketing, illustration, and more.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://www.skillshare.com/en/join/af/?clickid=xDK3V%3Ay8DxyZUqLxnr1IDVlsUkuVquy2cxbxSU0&irgwc=1&afsrc=1&utm_content=4650&utm_term=FreeForStudents&utm_campaign=2032346&affiliateRef=6595003&utm_medium=affiliate-referral&utm_source=IR&coupon=AFF30D25&ir_partnerid=2032346&ir_adid=1042864&ir_campaignid=4650',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'skillshare-30pc-annual';

update listings set
  description = 'Students save 50% on the first year of Squarespace. Build a portfolio, blog, or project site with professional templates and drag-and-drop editing.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://freeforstudents.org/row/templates/get-started',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'squarespace-50pc';

update listings set
  description = 'Save 15% on Airalo eSIMs for international travel. Stay connected abroad without swapping SIM cards or paying expensive roaming fees.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://www.airalo.com/?code=NEWTOAIRALO15&irclickid=x%3ArwuWy8DxyZUqLxnr1IDVlsUkuVquyfcxbxSU0&irgwc=1&afsrc=1&utm_source=impact&utm_medium=affiliate&utm_campaign=FreeForStudents&utm_content=&utm_term=',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'airalo-15pc';

update listings set
  description = 'Students and educators get free access to Autodesk design software including AutoCAD, Fusion 360, and Maya. Verify student status annually to keep access.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://freeforstudents.org/go/autodesk-edu-access',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'autodesk-edu-access';

update listings set
  description = 'College students get Hulu (With Ads) for $1.99/month while enrolled—about 83% off the regular price. Verify through SheerID; cancel anytime.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://freeforstudents.org/row/commerce/student?pref=hulu_basic',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'hulu-199';

update listings set
  description = 'Figma and FigJam are free for students and educators. Design, prototype, and collaborate in real time—plus Dev Mode for learning how designs translate to code.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://www.figma.com/community',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'figma-education-plan';

update listings set
  description = 'Students save 85% on Headspace. Access meditation, sleep, and mindfulness tools to manage stress and burnout during the semester.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://checkout.headspace.com/checkout?voucherCode=STUDENTL',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'headspace-student-plan';

update listings set
  description = 'Eligible students get Microsoft 365 apps—Word, Excel, PowerPoint, and OneNote—free with a valid school email. Sign in with your institutional account to get started.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://www.microsoft.com/en-us/education/products/office',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'free-msft-365';

update listings set
  description = 'Students save 40% on Evernote Professional. Organize lecture notes, assignments, and group projects in one searchable workspace across all your devices.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://accounts.evernote.com/registration?redirect_to=https%3A%2F%2Fevernote.com%2Fdownload-evernote',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'evernote-40pc-professional';

update listings set
  description = 'Students save 50% on Lingvist. Learn vocabulary in context with short, focused sessions designed to help you pick up a new language faster.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://freeforstudents.org/row#students-steps',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'lingvist-50pc';

update listings set
  description = 'Try Quizlet Plus free for 7 days. Unlock ad-free studying, offline mode, and advanced learning tools to prep for exams and quizzes.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://quizlet.com/upgrade',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'quizlet-plus';

update listings set
  description = 'Kickresume offers students up to 180 days of Premium free. Build ATS-friendly resumes and cover letters—verify with ISIC, ITIC, or UNiDAYS.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://freeforstudents.org/row/en/help-center/how-to-start-a-cover-letter',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'free-resume-builder';

update listings set
  description = 'Students save 25% on Blinkist Premium. Get key insights from thousands of nonfiction books and podcasts in about 15 minutes.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://www.blinkist.com/pricing/coupon/keeplearning_affiliates40_2026?irclickid=wuUzM6y8DxyZTrx0vtSVEx7RUkuVquQXcxbxSU0&irgwc=1&afsrc=1&utm_medium=paid&utm_campaign=2032346&utm_source=Impact&utm_term=25%25%20Off%20Blinkist%20Premium%20%28EN%29&utm_content=10732',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'blinkist-premium-25pc';

update listings set
  description = 'Craft gives students a free note-taking app with offline support, course organization, and collaboration. Ideal for lectures, research, and group projects.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://freeforstudents.org/row/download',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'craft-for-education';

update listings set
  description = 'Students save 25% on a one-year Medium membership. Read unlimited stories from writers across tech, culture, business, and more.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://help.medium.com/hc/articles/12846216085143-Redeeming-student-discounts',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'medium-25pc';

update listings set
  description = 'Students save 66% on Peacock streaming. Watch movies, TV, and live sports—stream on 3 devices and create up to 6 profiles.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://www.peacocktv.com/plans/all-monthly',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'peacock-66pc';

update listings set
  description = 'Jotform offers students unlimited survey submissions on its free education plan. Build custom forms for research, clubs, events, and class projects.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://freeforstudents.org/row/widgets',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'jotform-edu';

update listings set
  description = 'Canva for Education is free for students. Create presentations, posters, social graphics, and more with thousands of templates and design tools.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://www.canva.com/education/students/',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'canva-free';

update listings set
  description = 'Students save 30% on select Kobo eBooks and audiobooks. Verify student status to browse discounted titles for class and leisure reading.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://www.kobo.com/student',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'rakuten-kobo-30pc';

update listings set
  description = 'Notion for Education is free for students. Organize classes, clubs, internships, and side projects in one flexible workspace.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://freeforstudents.org/row/signup',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'notion-edu';

update listings set
  description = 'Students get 45% off plus free shipping at MYPROTEIN with code MYPBEANS. Stock up on protein, snacks, and wellness supplements.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://freeforstudents.org/row/c/dietary-needs/vegetarian',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = '45pc-myprotein';

update listings set
  description = 'Students receive $100 in Azure credit plus free access to popular cloud services. Build apps, host projects, and experiment with cloud tools at no cost.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://azure.microsoft.com/en-us/free/students/',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'azure-for-students';

update listings set
  description = 'Students save up to 40% on HP laptops, printers, and accessories. Verify enrollment to access education pricing on back-to-school tech.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://freeforstudents.org/go/40pc-hp-student',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = '40pc-hp-student';

update listings set
  description = 'Save up to $50 on Logitech back-to-school gear. Keyboards, mice, webcams, and headsets for your dorm desk or home setup.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://www.logitech.com/en-us/campaigns/back-to-school?irclickid=yhhWQ8y8DxyZUqLxnr1IDVlsUkuVqr0ecxbxSU0&utm_source=radius&utm_medium=affiliate&irgwc=1&afsrc=1',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'logitech-bts-24';

update listings set
  description = 'New Chegg Study subscribers save 25% on the first month. Get step-by-step textbook solutions and expert Q&A for tough assignments.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://www.chegg.com?irclickid=yMk373y8DxyZUqLxnr1IDVlsUkuVqrxGcxbxSU0&sharedid=&utm_medium=affiliate&utm_source=FreeForStudents&utm_campaign=Generic%2025%25%20off%20on%20CS%2FP%20-%202023&irgwc=1&afsrc=1',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = '25pc-chegg-study';

update listings set
  description = 'Fotor offers free online photo editing for students. Touch up images, remove backgrounds, and create graphics for projects and social media.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://fotor.sjv.io/MmLX73',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'fotor-free';

update listings set
  description = 'Save 21% on nutribullet blenders. Quick smoothies and shakes for busy mornings between classes and late study nights.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://www.nutribullet.com/getting-started/',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = '21pc-nutribullet';

update listings set
  description = 'Students and educators get free Lucidchart Education accounts. Create flowcharts, diagrams, and process maps with real-time collaboration.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://training.lucid.co/page/getting-started',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'lucidchart-edu';

update listings set
  description = 'Save up to 90% on textbooks with Chegg. Rent or buy used books and eTextbooks instead of paying full campus bookstore prices.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://www.chegg.com/books',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'chegg-books';

update listings set
  description = 'Students save 50% on any Chess.com Premium plan. Verify with UNiDAYS to unlock unlimited puzzles, lessons, game review, and ad-free play.',
  tags = array['Deals', 'Online'],
  listing_type = 'deal',
  source_url = 'https://www.chess.com/student-discount',
  cta_label = 'Get Deal',
  updated_at = now()
where slug = 'chess-com-50pc-premium';

commit;
